[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"
